print("------------------------------------------------")
print("|                                                |")
print("|    03GoodbyePerson                             |")
print("|    Name : Yiqing                               |")
print("|    Version : 01                                |")
print("|                                                |")
print("------------------------------------------------")
print("Hello")
personname=input(What is your name ?)
print("goodbye" + personname)
